config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [ :new, :create ]
  end
  resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end
  def create
    @bookmark = Bookmark.create(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save

      redirect_to list_path(@list)
    else
      render :new
    end
  end
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end
  def show
    @list = List.find(params[:id])
  end
  def new
    @list = List.new
  end
  def create
    @list = List.create(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [ @list, @bookmark ] do |f| %>
<%= f.input :comment %>
<%= f.input :movie_id, collection: Movie.all %>

<%= f.submit "Submit list" %>
<% end %>

<%= Bookmark.all %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="card-header bg-white d-flex justify-content-between">
      <div class="">
        <div class=""><img src="https://www.mcicon.com/wp-content/uploads/2021/01/Music_Movie_1-copy-2.jpg" alt="logo" width="40px" height="40px"></div>
      </div>
      <div class="d-flex">
        <div><%= link_to "My Lists", lists_path(@lists), class: "nav-link text-dark" %></div>
        <div><%= link_to "New List", new_list_path(@list), class: "nav-link text-dark" %></div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://c1.wallpaperflare.com/preview/570/413/91/interior-theatre-theater-empty-theater.jpg);">
  <div class="container">
    <h1 class="d-flex justify-content-center">Save any kind of movies</h1>
    <p class="d-flex justify-content-center">classic</p>
  </div>
</div>

  <div class="d-flex justify-content-between m-3 p-3">
    <h4>My Lists</h4>
    <h4><%= link_to "Create a movie list", new_list_path(@list), class: "btn btn-success text-white" %></h4>
  </div>





<div class="cards m-3">
  <% @lists.each do |list| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
      <%= link_to list.name, list_path(list), class: "nav-link text-white" %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= simple_form_for [ @list ] do |f| %>
<%= f.input :name %>
<%= f.submit "Submit list" %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<p></p>
<p><%= link_to "Main Page", lists_path() %></p>